server:
  port: ${PORT:3000}
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

gemini:
  api-key: ${GEMINI_API_KEY}
  api-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/entrenaback}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:123andi123}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
